### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by makachanm** [1-EXON/Learn-SQL#11]
미안하다 이거 보여주려고 어그로끌엇다... 러스트 고랭 싸움 수준 ㄹㅇ 실화냐? 진짜 세계관채강자들의싸움이다.... 그찐따같은러스트가맞냐??? 
![image](https://user-images.githubusercontent.com/55223245/80913666-4bc94280-8d81-11ea-826d-0a3a6c2bf269.png)

**Comment by sihyeokpark** [comment]
아닠ㅋㅋㅋ 마카도 왔어
