### ISSUE TITLE
충격기괴공포)) 웨이브사장엑슨이PPAP춤추면서언더테일노래를부르며천도씨쇠구글엑괴를먹방하다?????????

### ISSUE THREAD

**Issue by makachanm** [1-EXON/Learn-SQL#13]
는 미안하다 이거 보여주려고 어그로 끌었다

![image](https://user-images.githubusercontent.com/55223245/80913714-c003e600-8d81-11ea-912e-a13045748934.png)

**이슈빔**

**Comment by sihyeokpark** [comment]
음 차단을 먹고 싶군요

**Comment by dya-only** [comment]
엌
