### ISSUE TITLE
[심각한 이슈] 심각한 이슈입니다. 엑슨님 꼭 봐주세요.

### ISSUE THREAD

**Issue by KateLin-BASIC** [1-EXON/Learn-SQL#19]
https://craftofcoding.files.wordpress.com/2013/10/pi_forspaghetti.jpg
[그림 1-1 THS 버그의 사진]

엑슨님이 너무 잘생겨서 코드들이 서로 엉키고 있습니다. 외국 보안 전문 업체인 메타엑슨플로잇에선 이 버그를 TooHandSomeBug, 줄여서 THS 버그라 부르더군요. 이건 심각한 보안 문제입니다. 이 코드들은 깃허브의 다른 Repository를 감염시킵니다. 일종의 '웜' 바이러스인 셈이죠. 엑슨님이 더이상 잘생겨지면 메타엑슨플로잇에서는 이 코드는 한 달 이내로 5,064,149,832,510,964,937,344,608 개의 Repository를 감염시킬 것으로 보고있습니다. 다시 한 번 경고 합니다. 이 것은 인류의 중대한 위험입니다. 우리는 깃허브가 없던 시대로 돌아갈지 모릅니다.

**Comment by noamboy2006** [comment]
히익 이거 수정안되면 감염안되게 엑슨님 언팔하고 스타도 때야겠네요

**Comment by KateLin-BASIC** [comment]
그렇죠 ㅠㅠ 현재 발견된 행동으로는 스타를 붙은 사람의 repository가 감염된다고 합니다;; ㅠㅠ

**Comment by sihyeokpark** [comment]
아 그 질병 제가 막는 법 알아냈습니다.
부계정을 새로파서 엑슨을 팔로우하고 엑슨의 모든 레포를 스타하면 자신은 전혀 감염되지 않는답니다

**Comment by noamboy2006** [comment]
> 아 그 질병 제가 막는 법 알아냈습니다.
> 부계정을 새로파서 엑슨을 팔로우하고 엑슨의 모든 레포를 스타하면 자신은 전혀 감염되지 않는답니다

음?

**Comment by sihyeokpark** [comment]
학계에서 증명된 사실입니다

**Comment by kellsthepenguin** [comment]
이사람들아 진짠줄알았다고욬ㅋㅋㅋㅋㅋㅋㅋ

**Comment by KateLin-BASIC** [comment]
진짭니다 (?)

**Comment by sihyeokpark** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
